### ISSUE TITLE
[WIP] Refactoring this Repo

### ISSUE THREAD

**Issue by ins0** [ins0/google-measurement-php-client#19]
I'm currently refactoring the complete class, since the first release was working but not so well programmed.

Any suggestions would be very welcome :)

**Comment by peterigz** [comment]
Hi, thanks for creating this class it's very helpful! I've just started using it to send transaction data after someone pays via PayPal. It would be useful if there was a way to get the current Google client id. Currently "fetchCurrentClientId" is a private function only used internally when the tracking data is sent. But with PayPal you need to send the CID to them in a custom field to get it back again and connect the transaction up (as the user obviously leaves the site to go to paypal, so it would be useful to have access to this. I just changed fetchCurrentClientId to public but you might consider something a bit tidier in a future version :-)

**Comment by ins0** [comment]
@peterigz thanks for your feedback i will update this tonight :+1:

**Comment by ins0** [comment]
@peterigz the changes are now on master look at 1b37fbdf88e98f77e4da78437129d14fedcb7d47

**Comment by peterigz** [comment]
Perfect, thanks.
