### ISSUE TITLE
sendMultipleTracking problems

### ISSUE THREAD

**Issue by psychowico** [ins0/google-measurement-php-client#26]
Hello.
When I trying to use `sendMultipleTracking` from your example the code are hanging forever in
`Racecore\GATracking\Client\Adapter\Socket@readConnection` method.
When I use simple `sendTracking` it work correct. any ideas?

**Comment by ins0** [comment]
Did you use the example code 1:1? Or could you please post your current code which results in this error.

**Comment by psychowico** [comment]
it's enough to get example code and change async flag.
`async => false`

**Comment by ins0** [comment]
Thanks @psychowico! There was an issue with reading the correct byte length. If you like to test the upcoming changes - replace this file temporary

https://github.com/ins0/google-measurement-php-client/blob/fix/26/src/Racecore/GATracking/Client/Adapter/Socket.php

**Comment by psychowico** [comment]
it works quite random now. 
when I run script few times, sometimes work properly, sometimes I got
`Server closed connection unexpectedly`.
I believe that when I send more that 2 tracking at once, it throw this error often.

**Comment by ins0** [comment]
Ok give it a second try - optimized some things

**Comment by catherinek** [comment]
Hello there, I'm having the same problem with sendMultipleTracking() (without the mentioned fix in Socket.php) with v2.1.0. 
I'm sending a total of 3 tracking - ecommerce transaction, ecommerce item and an event, but none got delivered. And sometimes, not always, I get the `Server closed connection unexpectedly` error.

After implementing the mentioned fix in Socket.php, it seems to work fine. 
Will this fix be merged back to master or be included in a tagged version?

**Comment by ins0** [comment]
My bad, i will merge this as soon i'm back home! Sry!

Am Freitag, 18. März 2016 schrieb Catherine Koo :

> Hello there, I'm having the same problem with sendMultipleTracking()
> (without the mentioned fix in Socket.php) with v2.1.0.
> I'm sending a total of 3 tracking - ecommerce transaction, ecommerce item
> and an event, but none got delivered. And sometimes, not always, I get the Server
> closed connection unexpectedly error.
>
> After implementing the mentioned fix in Socket.php, it seems to work fine.
> Will this fix be merged back to master or be included in a tagged version?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ins0/google-measurement-php-client/issues/26#issuecomment-198515202>
>


-- 


_____________________
Marco Rieger
Flachsstraße 16
32369 Rahden
Germany

0171-5540818

https://racecore.de <http://racecore.de/>

**Comment by ins0** [comment]
@psychowico @catherinek merged - sry totaly forget this issue - ty for reminding me :+1:

**Comment by psychowico** [comment]
thanks for you work!

**Comment by catherinek** [comment]
Thank you! Much appreciated :+1:
