### ISSUE TITLE
Suddendly stopped working - Analytics Host not reachable!

### ISSUE THREAD

**Issue by coccoinomane** [ins0/google-measurement-php-client#37]
After years of honoured service, the library is throwing this error:

```
[01-Jul-2019 09:21:16 UTC] PHP Fatal error:  Uncaught Racecore\GATracking\Exception\EndpointServerException: Analytics Host not reachable! Error: Connection timed out in /home/meat/public_html/wp-content/plugins/wordpress-analytics/vendor/ins0/google-measurement-php-client/src/Racecore/GATracking/Client/Adapter/Socket.php:35
```

I first thought the problem was due to the GA-collect endpoint being hard-coded without HTTPS, but fixing that does not fix the error.

Does anybody have the same issue?

Cheers,
Guido

**Comment by ins0** [comment]
Can't confirm the error on my backends, the analytics data is send correctly to Google Analytics. Looks like something is blocking or intercepting the connection to `www.google-analytics.com/collect` on your server. Anything changed on the server side?

**Comment by coccoinomane** [comment]
Thank you @ins0 for your reply, and sorry for my late answer.
Nothing changed on the backend.
Since I opened the issue, the problem occurred on other websites and later disappeared.
I think it might have been some problem experienced by Google's datacenters close to my location.
I have not experienced the same issue since :-)
I am closing the issue.

Thank you and have a nice day,
Guido
